#!/usr/bin/env bash
# Extra media for the non-reference skip identity gate (FFmpeg is a test tool only).
# Written outside fixtures/ so committed fixtures are never regenerated by a different FFmpeg.
set -euo pipefail
D="${1:-${TENZOR_GEN_FIXTURES:-/tmp/tenzor-skip-fixtures}}"
mkdir -p "$D"
cd "$D"
F="ffmpeg -hide_banner -loglevel error -y"
SRC="testsrc2=size=640x360:rate=30"
AUD="aevalsrc=0.3*sin(2*PI*440*t)|0.2*sin(2*PI*880*t):s=48000"
x264() { echo -c:v libx264 -threads 2 -preset veryfast -pix_fmt yuv420p "$@"; }

# Same recipes as generate_matrix.py --long and gen_v018_fixtures.sh.
$F -f lavfi -i "$SRC:duration=30" -f lavfi -i "$AUD:d=30" $(x264 -profile:v high -bf 3 -g 60) -c:a aac -b:a 128k -movflags +faststart long-30.mp4
$F -f lavfi -i "$SRC:duration=330" -f lavfi -i "$AUD:d=330" $(x264 -profile:v high -bf 3 -g 60) -c:a aac -b:a 128k -movflags +faststart long-330.mp4
$F -f lavfi -i "testsrc2=size=1280x720:rate=30:duration=20" $(x264 -bf 3 -g 250 -keyint_min 10 -sc_threshold 40 -x264-params open-gop=1) gen-open-gop.mp4
$F -f lavfi -i "testsrc2=size=1280x720:rate=30:duration=12" $(x264 -bf 3 -g 45) gen-720-g45.mp4
$F -f lavfi -i "testsrc2=size=640x360:rate=24:duration=8" $(x264 -profile:v baseline -bf 0 -g 12) gen-baseline-g12.mp4

# B-frame structures that change which pictures are disposable.
$F -f lavfi -i "$SRC:duration=10" -f lavfi -i "$AUD:d=10" $(x264 -bf 3 -g 60 -x264-params b-pyramid=none) -c:a aac skip-bpyramid-none.mp4
$F -f lavfi -i "$SRC:duration=10" -f lavfi -i "$AUD:d=10" $(x264 -bf 3 -g 60 -x264-params b-pyramid=strict) -c:a aac skip-bpyramid-strict.mp4
$F -f lavfi -i "$SRC:duration=10" $(x264 -bf 16 -b_strategy 0 -g 90 -x264-params b-pyramid=normal) skip-bf16.mp4
$F -f lavfi -i "$SRC:duration=10" $(x264 -bf 2 -refs 1 -g 30 -x264-params b-adapt=2) skip-refs1-badapt.mp4
# 23.976 fps: epoch midpoints never align with frame times.
$F -f lavfi -i "testsrc2=size=640x360:rate=24000/1001:duration=9.3" -f lavfi -i "$AUD:d=9.3" $(x264 -bf 3 -g 48) -c:a aac skip-23976.mp4
# Irregular frame gaps with B-frame reordering.
$F -f lavfi -i "$SRC:duration=6.27" -vf "select='eq(mod(n\,7)\,0)+eq(mod(n\,11)\,0)+lt(n\,20)'" -fps_mode vfr $(x264 -bf 3 -g 30) skip-vfr.mp4
# Audio longer than video: final picture repeats through the tail.
$F -f lavfi -i "$SRC:duration=4" -f lavfi -i "$AUD:d=6.5" $(x264 -bf 3 -g 30) -c:a aac skip-audio-tail.mp4
# AAC music with 360p video from the v0.2.0 audio set.
$F -f lavfi -i "$SRC:duration=40" -f lavfi -i "$AUD:d=40" $(x264 -bf 3 -g 60) -c:a aac -b:a 192k -shortest av-music.mp4

echo "Generated $(ls "$D" | wc -l) files in $D"
