#!/usr/bin/env python3
"""Cross-architecture determinism gate: the same input must give the same bytes everywhere.

The engine promises bit-identical tensors for a given architecture, across any number of
workers, any chunk size and any number of repeats. Digests are recorded per architecture
and re-checked on every machine of that kind, so a regression on an ARM64 runner, an Apple
Silicon laptop or a Jetson is caught against that architecture's own reference.

Cross-architecture agreement is a numeric claim, not a byte one, and lives in
scripts/test_arch_tolerance.py.

    python3 scripts/test_arch_identity.py --record    # write evidence/arch-digests-<machine>.json
    python3 scripts/test_arch_identity.py             # verify this machine against it

Records the host architecture, the fixture digests, and the decode settings used. A
digest mismatch means the two machines disagree about a tensor, which is a bug, not a
tolerance.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import platform
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
BINARY = ROOT / "target/release/tenzor"
# Binary determinism is an intra-architecture guarantee: the same machine type must give
# the same bytes for any worker count, chunk size or repeat. Across architectures the FFT
# backend differs (AVX2 vs NEON) and the results round differently, which is measured by
# scripts/test_arch_tolerance.py instead. Each architecture therefore keeps its own file.
RECORD = ROOT / f"evidence/arch-digests-{platform.machine()}.json"
# (fixture, extra arguments). Every codec path, both decode modes and the audio-only
# path, so an architecture difference anywhere shows up here.
CASES = [
    ("fixture-h264-aac.mp4", []),
    ("fixture-h264-aac.mp4", ["--video-workers", "1"]),
    ("fixture-h264-aac.mp4", ["--video-workers", "4", "--chunk-target-ms", "250"]),
    ("fixture-h264-aac.mp4", ["--no-skip-nonref"]),
    ("high-bframes.mp4", ["--resolution", "160", "--window-sec", "0.33"]),
    ("baseline720.mp4", []),
    ("color709.mp4", []),
    ("fullrange.mp4", []),
    ("selection-vfr.mp4", []),
    ("selection-sparse.mp4", []),
    ("sync-pulse.mp4", []),
    # The silence-padded tail is arithmetic too: pin it like any other tensor path.
    ("audio-truncated-pts.mp4", []),
    ("aac-6ch.mp4", []),
    ("audio-only.mp4", []),
    ("wav-44100-2ch.wav", []),
    ("wav-48000-6ch.wav", ["--window-sec", "0.05", "--batch-epochs", "4"]),
    ("hevc-av.mp4", []),
    ("hevc-av.mp4", ["--video-workers", "1"]),
    ("hevc-av.mp4", ["--video-workers", "4", "--chunk-target-ms", "500"]),
    ("hevc-av.mp4", ["--no-skip-nonref"]),
    ("hevc-720.mp4", []),
    ("hevc-bt709.mp4", ["--execution", "sequential"]),
    # 1080p High profile: the only committed clips where the 8x8 transform carries most of
    # the residual, so they are what pins the SIMD 8x8 kernel by digest rather than by
    # differential test. Both GOP settings, because the GOP sets the chunk count.
    ("tests/data/benchmark_1080p.mp4", ["--video-workers", "2"]),
    ("tests/data/benchmark_1080p_gop250.mp4", ["--video-workers", "2"]),
]


def source_path(fixture: str) -> pathlib.Path:
    """Fixture names are relative to fixtures/; anything with a slash is repo-relative."""
    return ROOT / fixture if "/" in fixture else ROOT / "fixtures" / fixture


def digest(fixture: str, extra: list[str], out_dir: pathlib.Path) -> str:
    source = source_path(fixture)
    if not source.exists():
        return "missing-fixture"  # reported as a skip, never as a difference
    out = out_dir / "case.tenzor"
    out.unlink(missing_ok=True)
    proc = subprocess.run(
        [str(BINARY), "-i", str(source), "-o", str(out), "-q", *extra],
        capture_output=True,
        text=True,
        timeout=900,
    )
    if proc.returncode != 0:
        return f"error: {proc.stderr.strip().splitlines()[:1]}"
    value = hashlib.sha256(out.read_bytes()).hexdigest()
    out.unlink(missing_ok=True)
    return value


# Fixtures generated by a script rather than committed. Their bytes depend on the encoder
# build that produced them, so a digest mismatch on one of these is far more likely to be
# fixture drift than an engine regression, and the recorded fixture hashes below say which.
DERIVED_PREFIXES = ("hevc-", "long-", "audio-tail-")


def fixture_digest(fixture: str) -> str | None:
    source = source_path(fixture)
    return hashlib.sha256(source.read_bytes()).hexdigest() if source.exists() else None


def host() -> dict:
    return {
        "machine": platform.machine(),
        "system": platform.system(),
        "python": platform.python_version(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--record", action="store_true", help="write the reference digests")
    parser.add_argument("--out", help="record to this path instead of this architecture's "
                                      "reference file, for review before it is committed")
    args = parser.parse_args()
    if not BINARY.exists():
        raise SystemExit(f"missing {BINARY}; build the release binary first")
    out_dir = pathlib.Path(tempfile.mkdtemp(prefix="arch-identity-"))
    results = {f"{fixture} {' '.join(extra)}".strip(): digest(fixture, extra, out_dir) for fixture, extra in CASES}
    # One entry per distinct fixture, so a mismatch can be attributed to the input.
    fixtures = {name: fixture_digest(name) for name, _ in CASES}
    fixtures = {name: value for name, value in fixtures.items() if value}
    case_fixture = {f"{name} {' '.join(extra)}".strip(): name for name, extra in CASES}

    if args.record:
        dest = pathlib.Path(args.out) if args.out else RECORD
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(
            json.dumps({"recorded_on": host(), "fixtures": fixtures, "digests": results}, indent=1) + "\n"
        )
        print(f"recorded {len(results)} digests from {host()['machine']} into {dest}")
        for key, value in results.items():
            print(f"  {value[:16]}  {key}")
        return 0

    if not RECORD.exists():
        raise SystemExit(f"missing {RECORD}; run with --record on the reference machine first")
    reference = json.loads(RECORD.read_text())
    expected = reference["digests"]
    recorded_fixtures = reference.get("fixtures", {})
    same = missing = different = 0
    for key, value in results.items():
        source = case_fixture[key]
        drifted = source in recorded_fixtures and recorded_fixtures[source] != fixtures.get(source)
        if value == "missing-fixture":
            print(f"SKIP {key}: fixture not generated on this machine")
            missing += 1
        elif key not in expected:
            print(f"SKIP {key}: not in the recorded set")
            missing += 1
        elif drifted:
            # The input is not the one that was recorded, so its output is not evidence
            # about this engine either way.
            print(f"SKIP {key}: {source} differs from the recorded one "
                  f"(regenerate it with the same encoder build, or re-record)")
            missing += 1
        elif expected[key] == value:
            same += 1
        else:
            different += 1
            print(f"FAIL {key}\n  recorded {expected[key]}\n  here     {value}")
            if source.startswith(DERIVED_PREFIXES) and source not in recorded_fixtures:
                print(f"  note: {source} is generated, not committed, and this record "
                      f"predates fixture hashes; a different encoder build would look like this")
    print(
        f"\n{host()['machine']} vs recorded {reference['recorded_on']['machine']}: "
        f"{same} identical, {different} different, {missing} skipped"
    )
    return 1 if different else 0


if __name__ == "__main__":
    sys.exit(main())
